spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pandora?currentSchema=identity_schema
    username: postgres
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  jwt:
    secret-key: "85mAhWnVBM"
server:
  port: 8080

pandora:
  services:
    subscription:
      url: http://localhost:8082