version: '3.1'

services:
  
  gateway:
    image: gatewaysd
    ports:
      - "4000:4000"
    cap_add:
      - NET_ADMIN
    networks:
      - pandora
    container_name: gateway

  cache:
    image: cachesd
    ports:
      - "4040:4040"
    cap_add:
      - NET_ADMIN
    networks:
      - pandora
    container_name: cache

  course-service:
    image: subjectsd
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - gateway
    cap_add:
      - NET_ADMIN
    networks:
      - pandora
    container_name: course-service

  user-service:
    image: usersd
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - gateway
    cap_add:
      - NET_ADMIN
    networks:
      - pandora
    container_name: user-service

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - pandora
    container_name: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8090:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
    networks:
      - pandora

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pandora
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pandora
    restart: unless-stopped

networks:
  pandora:
    driver: bridge

volumes:
  postgres:
  pgadmin:
