version: '3.1'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    restart: always
    container_name: keycloak
    command:
        - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: identity_schema
    volumes:
        - ./keycloak/realm.json:/tmp/realm.json
        - ./keycloak/themes:/opt/jboss/keycloak/themes
    ports:
        - "8080:8080"
    networks:
      - pandora

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - pandora
    container_name: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8090:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
    container_name: mongo-express
    networks:
      - pandora

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pandora
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pandora
    restart: unless-stopped

networks:
  pandora:
    driver: bridge

volumes:
  postgres:
  pgadmin:
