spring:
  data:
    mongodb:
      host: "127.0.0.1"
      port: "27017"
      authentication-database: "admin"
      username: "admin"
      password: "password"
      database: "coursedb"

server:
  port: 8082