spring:
  data:
    mongodb:
      host: "mongo"
      port: "27017"
      authentication-database: "admin"
      username: "admin"
      password: "password"
      database: "coursedb"

  banner:
    location: classpath:banner.txt
server:
  port: 8444

pandora:
  services:
    gateway:
      url: "http://gateway:4000"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
