spring:
  profiles:
    active: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/pandora?currentSchema=identity_schema
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  banner:
    location: classpath:banner.txt
server:
  port: 8443

security:
  jwt:
    secret: "#sa55NZmpY8)&JGSXkG6sCh3vmLfjdRZ"

pandora:
  services:
    course-service:
      url: "http://course-service:8444"
    gateway:
      url: "http://gateway:4000"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
